language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install -r requirements_test.txt"
script: py.test tests -vrsx --cov app --pylama
after_success:
  - coveralls